version: "3.3"
services:
  eureka-server:
    image: "device-service:latest"
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: device-service
    volumes:
    - /opt/device-service:/opt/device/device-service
    network_mode: host
    ports:
      - "9003:9003"
    extra_hosts:
      - "host:192.168.3.31"
    healthcheck:
      test: curl --fail -s http://localhost:9003/actuator/health || exit 1
      interval: 30s
      timeout: 2m
      retries: 3
#    networks:
#      - host
